AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This serverless application is an example of using the Amazon SNS Fork pipelines in an e-commerce use case.

Parameters:
  LogLevel:
    Type: String
    Description: Log level for Lambda function logging, e.g., ERROR, INFO, DEBUG, etc
    Default: INFO

Resources:
  CheckoutApiBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: api.checkout
      Runtime: python3.6
      Tracing: Active
      Timeout: 5
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          TOPIC_ARN: !Ref CheckoutEventsTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt CheckoutEventsTopic.TopicName
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /checkout
            Method: post

  RemoveSensitiveDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: remove_sensitive_data.handler
      Runtime: python3.6
      Tracing: Active
      Timeout: 60
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel

  CheckoutEventsTopic:
    Type: AWS::SNS::Topic

  CheckoutPipeline:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../checkout-pipeline/dist/template.yml
      Parameters:
        SNSTopicArn: !Ref CheckoutEventsTopic
        LogLevel: !Ref LogLevel

  ReplayPipeline:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../../../pipelines/event-replay-pipeline/dist/template.yml
      Parameters:
        LogLevel: !Ref LogLevel
        SNSTopicArn: !Ref CheckoutEventsTopic
        DestinationSQSQueueName: !GetAtt CheckoutPipeline.Outputs.CheckoutQueueName
        ReplayQueueRetentionPeriodInSeconds: '1209600'

  BackupPipeline:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../../../pipelines/event-storage-backup-pipeline/dist/template.yml
      Parameters:
        LogLevel: !Ref LogLevel
        SNSTopicArn: !Ref CheckoutEventsTopic
        BackupCompressionFormat: GZIP
        DataTransformationLambdaFunctionArn: !GetAtt RemoveSensitiveDataFunction.Arn
        BufferingIntervalInSeconds: '60'
        BufferingSizeInMBs: '5'
        EnableBucketEncryption: 'true'

  AnalyticsPipeline:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../../../pipelines/event-search-analytics-pipeline/dist/template.yml
      Parameters:
        LogLevel: !Ref LogLevel
        SNSTopicArn: !Ref CheckoutEventsTopic
        ElasticsearchIndexName: checkout_events
        ElasticsearchTypeName: checkout
        RetryDurationInSeconds: '30'
        DataTransformationLambdaFunctionArn: !GetAtt RemoveSensitiveDataFunction.Arn
        BufferingIntervalInSeconds: '60'
        BufferingSizeInMBs: '5'
        SubscriptionFilterPolicy: |
          {
              "amount": [
                  { "numeric": [ ">=", 100 ] }
              ]
          }

Outputs:
  CheckoutApiUri:
    Description: Checkout API Prod stage URI
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/checkout
  CheckoutApiBackendFunctionName:
    Description: Checkout API handler Function Name
    Value: !Ref CheckoutApiBackendFunction
  CheckoutApiBackendFunctionArn:
    Description: Checkout API handler Function ARN
    Value: !GetAtt CheckoutApiBackendFunction.Arn
  CheckoutEventsTopicName:
    Description: Checkout events SNS topic name
    Value: !GetAtt CheckoutEventsTopic.TopicName
  CheckoutEventsTopicArn:
    Description: Checkout events SNS topic ARN
    Value: !Ref CheckoutEventsTopic
